-- 코드를 입력하세요
SELECT A.AUTHOR_ID AS AUTHOR_ID,
        B.AUTHOR_NAME AS AUTHOR_NAME,
        A.CATEGORY AS CATEGORY, 
        SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK AS A JOIN AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID JOIN BOOK_SALES AS C ON A.BOOK_ID = C.BOOK_ID
WHERE C.SALES_DATE LIKE '2022-01%'
GROUP BY A.CATEGORY, A.AUTHOR_ID
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC;