SELECT MCDP_CD '진료과코드', COUNT(*) '5월예약건수'
FROM APPOINTMENT
WHERE YEAR(APNT_YMD) = '2022' AND MONTH(APNT_YMD) = '05'
GROUP BY MCDP_CD
ORDER BY COUNT(*), MCDP_CD;














# SELECT MCDP_CD '진료과코드', COUNT(*) '5월예약건수'
# FROM APPOINTMENT
# WHERE YEAR(APNT_YMD) = 2022 AND MONTH(APNT_YMD) = 05
# GROUP BY MCDP_CD
# ORDER BY COUNT(*), MCDP_CD;