SELECT 
  YEAR(D1.DIFFERENTIATION_DATE) AS YEAR,
  M.MAX_SIZE - D1.SIZE_OF_COLONY AS YEAR_DEV,
  D1.ID
FROM ECOLI_DATA D1
JOIN (
  SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
  FROM ECOLI_DATA
  GROUP BY YEAR(DIFFERENTIATION_DATE)
) M
ON YEAR(D1.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV;